apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - image: rgy.k8s.devops-svc-ag.com/polytech/vote:1.0.1
          name: vote
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          env:
            - name: REDIS_CONNECTION_STRING
              value: redis://redis
            - name: OPTION_A
              value: Cats
            - name: OPTION_B
              value: Dogs
